// Mocks generated by Mockito 5.4.6 from annotations
// in tall_us/test/features/message/presentation/providers/message_providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tall_us/features/message/data/datasources/message_remote_datasource.dart'
    as _i3;
import 'package:tall_us/features/message/domain/entities/message_entity.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMessageEntity_0 extends _i1.SmartFake implements _i2.MessageEntity {
  _FakeMessageEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MessageRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageRemoteDataSource extends _i1.Mock
    implements _i3.MessageRemoteDataSource {
  MockMessageRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.MessageEntity> sendMessage({
    required String? matchId,
    required String? senderId,
    required String? receiverId,
    required String? content,
    _i2.MessageType? type = _i2.MessageType.text,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [],
          {
            #matchId: matchId,
            #senderId: senderId,
            #receiverId: receiverId,
            #content: content,
            #type: type,
          },
        ),
        returnValue: _i4.Future<_i2.MessageEntity>.value(_FakeMessageEntity_0(
          this,
          Invocation.method(
            #sendMessage,
            [],
            {
              #matchId: matchId,
              #senderId: senderId,
              #receiverId: receiverId,
              #content: content,
              #type: type,
            },
          ),
        )),
      ) as _i4.Future<_i2.MessageEntity>);

  @override
  _i4.Future<List<_i2.MessageEntity>> getMessages(String? matchId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessages,
          [matchId],
        ),
        returnValue:
            _i4.Future<List<_i2.MessageEntity>>.value(<_i2.MessageEntity>[]),
      ) as _i4.Future<List<_i2.MessageEntity>>);

  @override
  _i4.Future<void> markAsRead(String? messageId) => (super.noSuchMethod(
        Invocation.method(
          #markAsRead,
          [messageId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void subscribeToMessages(
    String? matchId,
    void Function(_i2.MessageEntity)? onMessage,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #subscribeToMessages,
          [
            matchId,
            onMessage,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unsubscribe() => super.noSuchMethod(
        Invocation.method(
          #unsubscribe,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
