// Mocks generated by Mockito 5.4.6 from annotations
// in tall_us/test/features/discovery/presentation/providers/discovery_extended_providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tall_us/core/errors/failures.dart' as _i8;
import 'package:tall_us/features/discovery/data/repositories/discovery_extended_repository.dart'
    as _i4;
import 'package:tall_us/features/discovery/domain/repositories/discovery_repository.dart'
    as _i7;
import 'package:tall_us/features/profile/domain/entities/user_profile_entity.dart'
    as _i6;
import 'package:tall_us/features/social/domain/entities/social_entities.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLikeRecord_0 extends _i1.SmartFake implements _i2.LikeRecord {
  _FakeLikeRecord_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePhotoMetadata_1 extends _i1.SmartFake implements _i2.PhotoMetadata {
  _FakePhotoMetadata_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_2<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DiscoveryExtendedRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiscoveryExtendedRepository extends _i1.Mock
    implements _i4.DiscoveryExtendedRepository {
  MockDiscoveryExtendedRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.LikeRecord> recordLike(_i2.LikeRecord? like) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordLike,
          [like],
        ),
        returnValue: _i5.Future<_i2.LikeRecord>.value(_FakeLikeRecord_0(
          this,
          Invocation.method(
            #recordLike,
            [like],
          ),
        )),
      ) as _i5.Future<_i2.LikeRecord>);

  @override
  _i5.Future<List<_i6.UserProfileEntity>> getWhoLikedMe(
    String? userId, {
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWhoLikedMe,
          [userId],
          {#limit: limit},
        ),
        returnValue: _i5.Future<List<_i6.UserProfileEntity>>.value(
            <_i6.UserProfileEntity>[]),
      ) as _i5.Future<List<_i6.UserProfileEntity>>);

  @override
  _i5.Future<void> markLikeAsSeen(String? likeId) => (super.noSuchMethod(
        Invocation.method(
          #markLikeAsSeen,
          [likeId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.TopPickScore>> getTopPicks(
    String? userId, {
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopPicks,
          [userId],
          {#limit: limit},
        ),
        returnValue:
            _i5.Future<List<_i2.TopPickScore>>.value(<_i2.TopPickScore>[]),
      ) as _i5.Future<List<_i2.TopPickScore>>);

  @override
  _i5.Future<void> saveTopPickScore(_i2.TopPickScore? score) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTopPickScore,
          [score],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> likePhoto(
    String? photoId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #likePhoto,
          [
            photoId,
            userId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> unlikePhoto(
    String? photoId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #unlikePhoto,
          [
            photoId,
            userId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> incrementPhotoViews(String? photoId) => (super.noSuchMethod(
        Invocation.method(
          #incrementPhotoViews,
          [photoId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> incrementPhotoMatches(String? photoId) =>
      (super.noSuchMethod(
        Invocation.method(
          #incrementPhotoMatches,
          [photoId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.PhotoMetadata> getPhotoMetadata(String? photoId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPhotoMetadata,
          [photoId],
        ),
        returnValue: _i5.Future<_i2.PhotoMetadata>.value(_FakePhotoMetadata_1(
          this,
          Invocation.method(
            #getPhotoMetadata,
            [photoId],
          ),
        )),
      ) as _i5.Future<_i2.PhotoMetadata>);

  @override
  _i5.Future<void> updatePhotoSmartScore(
    String? photoId,
    double? newScore,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePhotoSmartScore,
          [
            photoId,
            newScore,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [DiscoveryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiscoveryRepository extends _i1.Mock
    implements _i7.DiscoveryRepository {
  MockDiscoveryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<
      _i3
      .Either<_i8.Failure, List<_i6.UserProfileEntity>>> getProfilesToDiscover({
    required String? userId,
    required int? minAge,
    required int? maxAge,
    required int? minHeightCm,
    required int? maxHeightCm,
    required List<String>? preferredGenders,
    required int? maxDistanceKm,
    required String? userCity,
    required String? userCountry,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfilesToDiscover,
          [],
          {
            #userId: userId,
            #minAge: minAge,
            #maxAge: maxAge,
            #minHeightCm: minHeightCm,
            #maxHeightCm: maxHeightCm,
            #preferredGenders: preferredGenders,
            #maxDistanceKm: maxDistanceKm,
            #userCity: userCity,
            #userCountry: userCountry,
            #limit: limit,
          },
        ),
        returnValue: _i5
            .Future<_i3.Either<_i8.Failure, List<_i6.UserProfileEntity>>>.value(
            _FakeEither_2<_i8.Failure, List<_i6.UserProfileEntity>>(
          this,
          Invocation.method(
            #getProfilesToDiscover,
            [],
            {
              #userId: userId,
              #minAge: minAge,
              #maxAge: maxAge,
              #minHeightCm: minHeightCm,
              #maxHeightCm: maxHeightCm,
              #preferredGenders: preferredGenders,
              #maxDistanceKm: maxDistanceKm,
              #userCity: userCity,
              #userCountry: userCountry,
              #limit: limit,
            },
          ),
        )),
      ) as _i5.Future<_i3.Either<_i8.Failure, List<_i6.UserProfileEntity>>>);
}
