// Mocks generated by Mockito 5.4.6 from annotations
// in tall_us/test/features/social/presentation/providers/social_providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tall_us/features/social/data/repositories/social_repository_impl.dart'
    as _i3;
import 'package:tall_us/features/social/domain/entities/social_entities.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSocialEvent_0 extends _i1.SmartFake implements _i2.SocialEvent {
  _FakeSocialEvent_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSocialGroup_1 extends _i1.SmartFake implements _i2.SocialGroup {
  _FakeSocialGroup_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SocialRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockSocialRepositoryImpl extends _i1.Mock
    implements _i3.SocialRepositoryImpl {
  MockSocialRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.SocialEvent> createEvent(_i2.SocialEvent? event) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEvent,
          [event],
        ),
        returnValue: _i4.Future<_i2.SocialEvent>.value(_FakeSocialEvent_0(
          this,
          Invocation.method(
            #createEvent,
            [event],
          ),
        )),
      ) as _i4.Future<_i2.SocialEvent>);

  @override
  _i4.Future<List<_i2.SocialEvent>> getEvents({
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEvents,
          [],
          {
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue:
            _i4.Future<List<_i2.SocialEvent>>.value(<_i2.SocialEvent>[]),
      ) as _i4.Future<List<_i2.SocialEvent>>);

  @override
  _i4.Future<void> joinEvent(
    String? eventId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #joinEvent,
          [
            eventId,
            userId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.SocialGroup> createGroup(_i2.SocialGroup? group) =>
      (super.noSuchMethod(
        Invocation.method(
          #createGroup,
          [group],
        ),
        returnValue: _i4.Future<_i2.SocialGroup>.value(_FakeSocialGroup_1(
          this,
          Invocation.method(
            #createGroup,
            [group],
          ),
        )),
      ) as _i4.Future<_i2.SocialGroup>);

  @override
  _i4.Future<List<_i2.SocialGroup>> getGroups({
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGroups,
          [],
          {
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue:
            _i4.Future<List<_i2.SocialGroup>>.value(<_i2.SocialGroup>[]),
      ) as _i4.Future<List<_i2.SocialGroup>>);

  @override
  _i4.Future<void> joinGroup(
    String? groupId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #joinGroup,
          [
            groupId,
            userId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getFriendsOfFriends(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFriendsOfFriends,
          [userId],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Stream<Map<String, dynamic>> subscribeToEventUpdates(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToEventUpdates,
          [eventId],
        ),
        returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
      ) as _i4.Stream<Map<String, dynamic>>);

  @override
  _i4.Stream<Map<String, dynamic>> subscribeToGroupUpdates(String? groupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToGroupUpdates,
          [groupId],
        ),
        returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
      ) as _i4.Stream<Map<String, dynamic>>);
}
