import 'package:flutter/material.dart';

/// Predefined interests for Tall Us (Tinder-style)
class TallInterests {
  static const Map<String, List<String>> interestsByCategory = {
    'Voyage': [
      'Plage',
      'Montagne',
      'Voyage',
      'Aventure',
      'Road trip',
      'Camping',
      'Croisière',
      'Backpacking',
      'Luxury travel',
      'Culture',
    ],
    'Sport': [
      'Fitness',
      'Yoga',
      'Running',
      'Football',
      'Rugby',
      'Basketball',
      'Tennis',
      'Natation',
      'Cyclisme',
      'Randonnée',
      'Ski',
      'Escalade',
      'Surf',
      'Golf',
      'Musculation',
      'Crossfit',
      'Pilates',
      'Danse',
      'Boxe',
      'Arts martiaux',
    ],
    'Musique': [
      'Concerts',
      'Festivals',
      'Rock',
      'Pop',
      'Jazz',
      'Hip-hop',
      'Électro',
      'Classique',
      'Rap',
      'Indie',
      'R&B',
      'Reggae',
      'Metal',
      'Country',
      'Musique live',
      'Karaoke',
    ],
    'Cuisine': [
      'Gastronomie',
      'Cuisine',
      'Pâtisserie',
      'Vins',
      'Café',
      'Restaurant',
      'Street food',
      'Végétarien',
      'Vegan',
      'Bio',
      'Cuisine italienne',
      'Cuisine française',
      'Cuisine asiatique',
      'Cuisine mexicaine',
    ],
    'Art & Culture': [
      'Cinéma',
      'Théâtre',
      'Musée',
      'Art',
      'Photographie',
      'Lecture',
      'Écriture',
      'Peinture',
      'Sculpture',
      'Design',
      'Architecture',
      'Histoire',
      'Philosophie',
      'Poésie',
      'Bande dessinée',
      'Anime',
      'Manga',
    ],
    ' divertissement': [
      'Jeux vidéo',
      'Streaming',
      'Séries TV',
      'Netflix',
      'YouTube',
      'Twitch',
      'Board games',
      'Escape games',
      'Casino',
      'Poker',
      'Quiz',
      'Karaoké',
      'Soirées',
      'Nightclub',
      'Bars',
    ],
    'Nature': [
      'Nature',
      'Animaux',
      'Chiens',
      'Chats',
      'Jardinage',
      'Pêche',
      'Chasse',
      'Écologie',
      'Camping',
      'Bord de mer',
      'Lacs',
      'Forêt',
      'Randonnée',
      'Observation des étoiles',
    ],
    'Technologie': [
      'Tech',
      'Informatique',
      'Programmation',
      'IA',
      'Gaming',
      'Crypto',
      'Startups',
      'Innovation',
      'Gadgets',
      'Smart home',
      'VR',
      'SpaceX',
      'Science',
      'Robotique',
    ],
    'Mode': [
      'Mode',
      'Shopping',
      'Luxe',
      'Streetwear',
      'Vintage',
      'Design',
      'Beauté',
      'Maquillage',
      'Coiffure',
      'Tattoos',
      'Piercings',
      'Accessoires',
      'Chaussures',
      'Sneakers',
    ],
    'Personnalité': [
      'Humour',
      'Sarcasme',
      'Ambiverti',
      'Introverti',
      'Extraverti',
      'Optimiste',
      'Aventureux',
      'Spontané',
      'Romantique',
      'Sérieux',
      'Curieux',
      'Créatif',
      'Spirituel',
      'Méditation',
      'Mindfulness',
    ],
    'Lifestyle': [
      'Entrepreneuriat',
      'Business',
      'Finance',
      'Investissement',
      'Immobilier',
      'Bourse',
      'Crypto',
      'Freelance',
      'Remote work',
      'Digital nomad',
      'Productivité',
      'Self-improvement',
      'Motivation',
      'Networking',
      'Mentoring',
    ],
    'Social': [
      'Bénévolat',
      'Activisme',
      'Politique',
      'Environnement',
      'Causes sociales',
      'Humanitaire',
      'Associations',
      'Charité',
      'Communauté',
      'Événements',
      'Rencontres',
      'Famille',
      'Enfants',
      'Mariage',
    ],
    'Tall spécific': [
      'Grand(e)',
      'Sport de grand(e)',
      'Vêtements pour grand(e)s',
      'Avantages de la taille',
      'Inconvénients de la taille',
      'Humour taille',
      'Confiance en soi',
      'Posture',
      'Basketball',
      'Volleyball',
      'Modélisation',
      'Mannequinat',
    ],
  };

  /// Get all interests as a flat list
  static List<String> get allInterests {
    return interestsByCategory.values.expand((e) => e).toList();
  }

  /// Get popular interests (first 50)
  static List<String> get popularInterests {
    return [
      'Voyage',
      'Photographie',
      'Cuisine',
      'Fitness',
      'Yoga',
      'Musique',
      'Cinéma',
      'Art',
      'Lecture',
      'Nature',
      'Animaux',
      'Aventure',
      'Randonnée',
      'Plage',
      'Séries TV',
      'Netflix',
      'Jeux vidéo',
      'Humour',
      'Ambiverti',
      'Spontané',
      'Entrepreneuriat',
      'Business',
      'Tech',
      'Gaming',
      'Mode',
      'Shopping',
      'Concerts',
      'Festivals',
      'Nightclub',
      'Soirées',
      'Chiens',
      'Chats',
      'Gastronomie',
      'Vins',
      'Café',
      'Sport',
      'Running',
      'Musculation',
      'Créatif',
      'Optimiste',
      'Romantique',
      'Activisme',
      'Environnement',
      'Bénévolat',
      'Sarcasme',
      'Netflix & chill',
      'Road trip',
      'Camping',
      'Ski',
      'Surf',
      'Basketball',
      'Grand(e)',
    ];
  }

  /// Get color for interest category
  static Color getCategoryColor(String category) {
    final colors = {
      'Voyage': const Color(0xFF4A90E2),
      'Sport': const Color(0xFF50E3C2),
      'Musique': const Color(0xFFB8E986),
      'Cuisine': const Color(0xFFF5A623),
      'Art & Culture': const Color(0xFF9013FE),
      'Divertissement': const Color(0xFFFF6B9D),
      'Nature': const Color(0xFF7ED321),
      'Technologie': const Color(0xFF4A4A4A),
      'Mode': const Color(0xFFBD10E0),
      'Personnalité': const Color(0xFFFF6F00),
      'Lifestyle': const Color(0xFF417505),
      'Social': const Color(0xFFD0021B),
      'Tall spécific': const Color(0xFF722F37),
    };
    return colors[category] ?? const Color(0xFF9B9B9B);
  }

  /// Get category for an interest
  static String? getCategoryForInterest(String interest) {
    for (var entry in interestsByCategory.entries) {
      if (entry.value.contains(interest)) {
        return entry.key;
      }
    }
    return null;
  }
}
